# Generated by Django 3.0.6 on 2020-05-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
