# Generated by Django 3.0.6 on 2020-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20200525_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.URLField(),
        ),
    ]
