# Generated by Django 3.0.6 on 2020-05-26 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
