# Generated by Django 3.0.6 on 2020-05-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20200526_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
